name: riversnap
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - cartopy
  - gdal
  - geopandas
  - matplotlib
  - numpy
  - pandas
  - pyflwdir
  - rasterio
  - scikit-learn
  - seaborn
  - shapely
  - tqdm
  - typer
