name: riversnap
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - geopandas
  - sqlalchemy
  - psycopg2
  - sphinx
  - sphinx-rtd-theme
  - nbsphinx
  - docutils<0.21
  - pip:
      - nbsphinx-link